### ISSUE TITLE
Texture only loading first pixel

### ISSUE THREAD

**Issue by Peluchomp** [CITM-UPC/HawkEngine#1]
@pepcots im trying to load the textures to a model with the code we did in class, but i saw that it only gets the information of the first pixel of the texture. Could it be because im passing the wrong texture coordinates? Also it never enters the buffer.ID() if statements in the draw function. 

Draw function:
https://github.com/CITM-UPC/HawkEngine/blob/f95ba7850f9f977d8d4c7f208c2c2ad5b882f453/MyGameMaker/MyGameEngine/Mesh.cpp#L50-L93

LoadMesh and texCoords:
https://github.com/CITM-UPC/HawkEngine/blob/f95ba7850f9f977d8d4c7f208c2c2ad5b882f453/MyGameMaker/MyGameEngine/Mesh.cpp#L96-L134

Load the actual texture from file:
https://github.com/CITM-UPC/HawkEngine/blob/f95ba7850f9f977d8d4c7f208c2c2ad5b882f453/MyGameMaker/MyGameEngine/Mesh.cpp#L137-L163

**Comment by pepcots** [comment]
Hello @Peluchomp.
Take care when loading mesh data the order is very important: first load vertices and indices, and then load texCoords and all the rest, because you need to load vertices first as this is the minimal information.
In your code, you are first loading texCoords and then loading vertices and indices:
https://github.com/CITM-UPC/HawkEngine/blob/f95ba7850f9f977d8d4c7f208c2c2ad5b882f453/MyGameMaker/MyGameEngine/Mesh.cpp#L96-L134

**Comment by Peluchomp** [comment]
Makes sense, thanks!
